#!/usr/bin/env bash
set -o errexit -o noclobber -o nounset

HUE=(-level 0%,100%,0.6)
EFFECT=(-scale 10% -scale 1000%)
FONT="$(convert -list font | awk "{ a[NR] = \$2 } /family: $(fc-match 'Hack Nerd Font Mono' -f "%{family}\n")/ { print a[NR-1]; exit }")"
IMAGE="$(mktemp).png"

OPTIONS="Options:
    -h, --help   This help menu."

# move pipefail down as for some reason "convert -list font" returns 1
set -o pipefail
trap 'rm -f "$IMAGE"' EXIT
TEMP="$(getopt -o :hpglf: -l help,pixelate,greyscale,font: --name "$0" -- "$@")"
eval set -- "$TEMP"

while true ; do
    case "$1" in
        -h|--help)
            printf "Usage: $(basename $0) [options]\n\n$OPTIONS\n\n" ; exit 1 ;;
        --) shift ; break ;;
        *) echo "error" ; exit 1 ;;
    esac
done

# get path where the script is located to find the lock icon
SCRIPTPATH=$(realpath "$0")
SCRIPTPATH=${SCRIPTPATH%/*}

# Display text
# FORTUNE="$(fortune debian science linux computers paradoxum linuxcookie goedel disclaimer debian-hints work | sed 's/\t/  /g')"
TRICKSTERS=("Pablo" "Nico" "Zach" "Jose" "Lars" "Ezgi" "Rodrigo" "Manuel" "Dimitris")
FORTUNE="$(fortune | sed 's/\t/  /g' | cowthink)"
TEXT="$FORTUNE\n\n\n...and that's why you'll never croissant me (again) ${TRICKSTERS[$RANDOM % ${#TRICKSTERS[@]} ]}!!"
VALUE="60"  # brightness value to compare to
scrot -z "$IMAGE"
COLOR=$(convert "$IMAGE" -gravity center -crop 100x100+0+0 +repage -colorspace hsb \
    -resize 1x1 txt:- | awk -F '[%$]' 'NR==2{gsub(",",""); printf "%.0f\n", $(NF-1)}');
if [ "$COLOR" -gt "$VALUE" ]; then  # white background image and black text
    BW="black"
else  # black
    BW="white"
fi

convert \
    "$IMAGE" "${HUE[@]}" "${EFFECT[@]}" \
    -font "$FONT" -pointsize 24 -fill "$BW" -gravity West -annotate +500+0 "$TEXT" "$IMAGE"

# Disable notifications
pkill -u "$USER" -USR1 dunst

# Pause music
playerctl status && player_running=$? || player_running=$?
if [ "$player_running" == 0 ]; then
    music_status="$(playerctl status)"
    if [ "$music_status" == "Playing" ]; then
        playerctl pause
    fi
fi

# Run the locker
i3lock -n -i "$IMAGE"

# resume message display
pkill -u "$USER" -USR2 dunst
# play music
if [ "$music_status" == "Playing" ]; then
    playerctl play
fi
