#!/home/aioannid/Envs/rofi-scripts/bin/python

import subprocess
from collections import namedtuple

from rofi import Rofi

ROFI = Rofi(rofi_args=["-i", "-sort"])


Account = namedtuple("Account", ("group", "name", "user", "id"))


def list_accounts():
    lpass_list = subprocess.check_output(
        'lpass ls --format "%ag|%an|%au|%ai"', shell=True, encoding="utf8"
    )
    accounts = (Account(*l.split("|")) for l in lpass_list.splitlines())
    return [a for a in accounts if a.name]


def select_account(accounts):
    index, key = ROFI.select(
        "Select an account", [f"{a.group} - {a.name} [{a.id}]" for a in accounts],
        sorted=True,
    )
    return accounts[index]


def put_in_clipboard(account):
    lpass_list = subprocess.check_call(
        f"lpass show --password --clip {account.id}", shell=True
    )


def main():
    try:
        accounts = list_accounts()
        selected_account = select_account(accounts)
        put_in_clipboard(selected_account)
    except Exception as ex:
        ROFI.exit_with_error(ex)


if __name__ == "__main__":
    main()
