#!/home/aioannid/Envs/rofi-scripts/bin/python

from rofi import Rofi
import subprocess
import sys


ROFI = Rofi()

# First scan for networks
wicd_scan_res = subprocess.run(['wicd-cli', '--wireless', '--scan'])
if wicd_scan_res.returncode != 0:
    ROFI.exit_with_error('Scan for wireless networks failed...')

# Fetch all network names
wicd_list_res = subprocess.run(
    ['wicd-cli', '--wireless', '--list-networks'],
    capture_output=True, encoding='utf8')

# networks are back in descending strength order, thus we want to keep only the
# strongest selection for each ESSIDs (i.e. network name)
networks = {}
for line in wicd_list_res.stdout.splitlines()[1:]:
    index, _, _, essid = line.split('\t')
    networks.setdefault(essid.strip(), int(index))

network_choices = sorted(networks, key=lambda k: networks[k])

# Prompt user for network
index, key = ROFI.select('Select a wireless network', network_choices)

if key == 0:
    network_index = networks[network_choices[index]]
    wicd_connect_res = subprocess.run(
        ['wicd-cli', '--wireless', '--connect', '--network', str(index)],
        capture_output=True, encoding='utf8')
    if wicd_connect_res.returncode != 0:
        ROFI.exit_with_error(
            f'Connection failed...\n'
            f'{wicd_connect_res.stdout}'
            f'{wicd_connect_res.stdout}')
